ALTER TABLE "sessions" ADD COLUMN IF NOT EXISTS "seoScore" INTEGER;
ALTER TABLE "sessions" ADD COLUMN IF NOT EXISTS "semrushData" JSONB;
ALTER TABLE "sessions" ADD COLUMN IF NOT EXISTS "googlePlacesData" JSONB;
ALTER TABLE "sessions" ADD COLUMN IF NOT EXISTS "tweetUrl" TEXT;
