import type { CandidateProfile } from "../types";

/**
 * Emod Vafa — candidate profile.
 *
 * Reconciled against the real resume (Emod_Vafa_Resume_2026.pdf), 2026-07-16.
 * BBA Marketing, Schulich School of Business (York), 2011. Currently Fractional
 * CMO at Banoo Marketing (2025–present); prior Director of Marketing at Intercap
 * Inc. (2022–2025). This is the single source of truth the pipeline scores
 * against.
 */
export const EMOD_VAFA: CandidateProfile = {
  name: "Emod Vafa",
  headline:
    "Director of Marketing | Performance & Growth Leader (15+ years)",
  location: "Toronto, ON",
  yearsExperience: 15,
  targetSalaryCad: 170_000,
  stretchSalaryCad: 250_000,
  openTo: ["full-time", "part-time", "contract", "fractional"],
  citizenshipNote: "Canadian Citizen — no sponsorship ever required",
  linkedin: "https://ca.linkedin.com/in/emodvafa",
  calendarLink: "cal.com/emodvafa",
  phone: "(416) 400-4699",
  email: "emadvafa@gmail.com",
  skills: [
    "demand generation",
    "performance marketing",
    "growth marketing",
    "revenue marketing",
    "google ads",
    "meta ads",
    "facebook ads",
    "linkedin ads",
    "programmatic",
    "dsp",
    "traffic arbitrage",
    "seo",
    "sem",
    "email marketing",
    "hubspot",
    "salesforce",
    "ga4",
    "close crm",
    "twilio",
    "mailgun",
    "sendgrid",
    "apollo.io",
    "instantly.ai",
    "ai automation",
    "openai",
    "claude",
    "gemini",
    "prompt engineering",
    "b2b",
    "gtm strategy",
    "lifecycle marketing",
    "acquisition",
    "affiliate marketing",
    "cro",
    "cac/ltv optimization",
    "multi-touch attribution",
    "roas",
    "team leadership",
  ],
  preferredIndustries: [
    "tech",
    "saas",
    "ai",
    "legal",
    "automotive",
    "real estate",
    "b2b",
    "cybersecurity",
    "fintech",
    "healthcare tech",
    "affiliate",
    "ecommerce",
    "skilled trades",
    "web3",
  ],
  targetTitles: [
    "director of marketing",
    "director of growth",
    "director of demand generation",
    "director of revenue marketing",
    "director of performance marketing",
    "director of b2b marketing",
    "director of gtm",
    "director of omni-channel marketing",
    "head of marketing",
    "head of growth",
    "head of media",
    "senior director of growth",
    "senior director of marketing",
    "brand marketing director",
    "digital marketing director",
    "director of global leads",
    "director of acquisition",
    "director of lifecycle marketing",
    "vp of marketing",
    "vp marketing",
    "chief marketing officer",
    "cmo",
  ],
};
