import type { CandidateProfile } from "../types";

/**
 * Emod Vafa — candidate profile.
 *
 * Sourced from the project brief. Once the real resume PDF
 * (Emod_Vafa_Resume_2026.pdf) is supplied, run `parseResume()` (TODO) to
 * reconcile/override these fields. Until then this is the single source of
 * truth the pipeline scores against.
 */
export const EMOD_VAFA: CandidateProfile = {
  name: "Emod Vafa",
  headline:
    "Director of Marketing | Performance & Growth Leader (15+ years)",
  location: "Toronto, ON",
  yearsExperience: 15,
  targetSalaryCad: 170_000,
  stretchSalaryCad: 250_000,
  openTo: ["full-time", "part-time", "contract", "fractional"],
  citizenshipNote: "Canadian Citizen — no sponsorship ever required",
  linkedin: "https://ca.linkedin.com/in/emodvafa",
  calendarLink: "cal.com/emodvafa",
  phone: "(416) 400-4699",
  email: "emadvafa@gmail.com",
  skills: [
    "demand generation",
    "performance marketing",
    "growth marketing",
    "revenue marketing",
    "google ads",
    "meta ads",
    "linkedin ads",
    "programmatic",
    "seo",
    "sem",
    "hubspot",
    "salesforce",
    "ga4",
    "close crm",
    "ai automation",
    "openai",
    "claude",
    "gemini",
    "b2b",
    "gtm strategy",
    "lifecycle marketing",
    "acquisition",
    "affiliate marketing",
    "roas",
    "team leadership",
  ],
  preferredIndustries: [
    "tech",
    "saas",
    "ai",
    "legal",
    "automotive",
    "real estate",
    "b2b",
    "cybersecurity",
    "fintech",
    "healthcare tech",
    "affiliate",
    "ecommerce",
    "skilled trades",
  ],
  targetTitles: [
    "director of marketing",
    "director of growth",
    "director of demand generation",
    "director of revenue marketing",
    "director of performance marketing",
    "director of b2b marketing",
    "director of gtm",
    "director of omni-channel marketing",
    "head of marketing",
    "head of growth",
    "head of media",
    "senior director of growth",
    "senior director of marketing",
    "brand marketing director",
    "digital marketing director",
    "director of global leads",
    "director of acquisition",
    "director of lifecycle marketing",
    "vp of marketing",
    "vp marketing",
    "chief marketing officer",
    "cmo",
  ],
};
